---
version: 2
updates:

  #----------------------------------------------------------------------------
  # Go - root directory
  #----------------------------------------------------------------------------

  - package-ecosystem: "gomod"
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      timezone: "Europe/Madrid"
      time: "08:00"
    ignore:
      - dependency-name: "sigs.k8s.io/controller-runtime"
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"
    groups:
      gomod:
        update-types: [minor, patch]

  #----------------------------------------------------------------------------
  # github-actions
  #----------------------------------------------------------------------------

  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      timezone: "Europe/Madrid"
      time: "08:00"
    groups:
      github-actions:
        update-types: [minor, patch]
