---
version: 2
updates:

  # Go - root directory 
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      timezone: "Europe/Madrid"
      time: "08:00"
    ignore:
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  # github-actions
  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      timezone: "Europe/Madrid"
      time: "08:00"
