# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

#------------------------------------------------------------------------------
# before
#------------------------------------------------------------------------------

before:
  hooks:
    - go mod tidy

#------------------------------------------------------------------------------
# builds
#------------------------------------------------------------------------------

builds:
  - id: swarmctl
    main: ./cmd/swarmctl
    binary: swarmctl
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X github.com/octoroot/k-swarm/cmd/swarmctl/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

#------------------------------------------------------------------------------
# archives
#------------------------------------------------------------------------------

archives:
  - id: swarmctl
    builds:
      - swarmctl
    format: binary
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}

#------------------------------------------------------------------------------
# changelog
#------------------------------------------------------------------------------

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

#------------------------------------------------------------------------------
# brews
#------------------------------------------------------------------------------

brews:
  - name: swarmctl
    ids:
      - swarmctl
    repository:
      owner: octoroot
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/octoroot/k-swarm
    description: A k8s service swarm
    license: MIT
    test: |
      system "#{bin}/swarmctl -v"
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: "../lib/custom_download_strategy"
