apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: dev-registry
kindV1Alpha4Cluster:
  name: dev
  nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock