apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default

patches:
  - path: ./patches/deployments/k-swarm-controller-manager.yaml
    target:
      kind: Deployment
      name: k-swarm-controller-manager
