apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-x
namePrefix:

resources:
- manager.yaml
- telemetry.yaml

images:
- name: controller
  newName: octoroot/k-swarm
  newTag: latest
