---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: swarm
    app.kubernetes.io/part-of: swarm
    app.kubernetes.io/managed-by: kustomize
    istio-injection: enabled
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: swarm
    app.kubernetes.io/part-of: swarm
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        swarm/informer: enabled
        swarm/worker: enabled
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect=false
        - --enable-informer=false
        - --enable-worker=true
        - --worker-bind-address=:8082
        - --informer-url=http://informer.informer
        - --informer-poll-interval=10s
        - --worker-request-interval=2s
        image: controller:latest
        name: manager
        env:
        - name: CLUSTER_NAME
          value: "kind-dev"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        ports:
        - containerPort: 8082
          name: worker
          protocol: TCP
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: swarm
spec:
  selector:
    swarm/worker: enabled
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: worker
