---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: service-x
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      swarm/worker: enabled
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        swarm/worker: enabled
    spec:
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        agentpool: nodepool2
      containers:
      - command:
        - /manager
        args:
        - --leader-elect=false
        - --enable-informer=false
        - --enable-worker=true
        - --worker-bind-address=:8082
        - --informer-url=http://informer.informer
        - --informer-poll-interval=60s
        - --worker-request-interval=2s
        image: controller:latest
        name: manager
        env:
        - name: CLUSTER_NAME
          value: "kind-dev"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        ports:
        - containerPort: 8082
          name: worker
          protocol: TCP
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: swarm
spec:
  selector:
    swarm/worker: enabled
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: worker
