apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    metadata:
      labels:
        swarm/informer: disabled
        swarm/worker: enabled
    spec:
      containers:
      - name: manager
        args:
        - --leader-elect=false
        - --enable-informer=false
        - --enable-worker=true
        - --worker-bind-address=:8082
        - --informer-url=http://swarm-informer.swarm-system
        - --informer-poll-interval=10s
        - --worker-request-interval=2s
