---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: service-x
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: informer
spec:
  selector:
    matchLabels:
      swarm/informer: enabled
  replicas: 2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        swarm/informer: enabled
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: swarm/informer
                operator: In
                values:
                - enabled
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        agentpool: nodepool1
      containers:
      - command:
        - /manager
        args:
        - --leader-elect=false
        - --enable-informer=true
        - --enable-worker=false
        - --informer-bind-address=:8083
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8083
          name: informer
          protocol: TCP
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: informer
spec:
  selector:
    swarm/informer: enabled
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: informer

