apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: service-x
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: swarm
  name: worker
  namespace: service-x
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: worker
  selector:
    swarm/worker: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: service-x
spec:
  replicas: 4
  selector:
    matchLabels:
      swarm/worker: enabled
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        swarm/worker: enabled
    spec:
      containers:
      - args:
        - --leader-elect=false
        - --enable-informer=false
        - --enable-worker=true
        - --worker-bind-address=:8082
        - --informer-url=http://informer.informer
        - --informer-poll-interval=60s
        - --worker-request-interval=2s
        command:
        - /manager
        env:
        - name: CLUSTER_NAME
          value: kind-dev
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: h0tbird/swarm:latest
        name: manager
        ports:
        - containerPort: 8082
          name: worker
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      nodeSelector:
        agentpool: nodepool2
      securityContext:
        runAsNonRoot: true
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: istio-metrics
  namespace: service-x
spec:
  metrics:
  - overrides:
    - disabled: true
      match:
        metric: ALL_METRICS
        mode: CLIENT_AND_SERVER
    providers:
    - name: prometheus
