name: Cleanup

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - "closed"

jobs:

  #----------------------------------------------------------------------------
  # Cleanup ephemeral images
  #----------------------------------------------------------------------------

  cleanup-ephemeral-images:

    name: Cleanup ephemeral images
    runs-on: ubuntu-latest

    steps:

    - name: Cleanup ephemeral images
      uses: stumpylog/image-cleaner-action/ephemeral@v0.5.0
      with:
        token: "${{ secrets.PACKAGE_DELETE_TOKEN }}"
        owner: "octoroot"
        is_org: "true"
        package_name: "k-swarm"
        scheme: "pull_request"
        repo_name: "k-swarm"
        match_regex: '^pr-(\d+)$|^(\d+)$'
        do_delete: "true"

  #----------------------------------------------------------------------------
  # Cleanup untagged images
  #----------------------------------------------------------------------------

  cleanup-untagged-images:

      name: Cleanup untagged images
      runs-on: ubuntu-latest
      needs: cleanup-ephemeral-images

      steps:

      - name: Clean untagged images
        uses: stumpylog/image-cleaner-action/untagged@v0.5.0
        with:
          token: "${{ secrets.PACKAGE_DELETE_TOKEN }}"
          owner: "octoroot"
          is_org: "true"
          package_name: "k-swarm"
          do_delete: "true"
