name: Cleanup old ghcr.io images

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - "closed"

jobs:

  #----------------------------------------------------------------------------
  # Cleanup ephemeral images
  #----------------------------------------------------------------------------

  cleanup-ephemeral-images:

    name: Cleanup ephemeral images
    runs-on: ubuntu-latest

    steps:

    - name: Log into registry ghcr.io
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_DELETE_TOKEN }}

    - name: Cleanup ephemeral images
      uses: stumpylog/image-cleaner-action/ephemeral@v0.10.0
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        owner: "h0tbird"
        is_org: "false"
        package_name: "k-swarm"
        scheme: "pull_request"
        repo_name: "k-swarm"
        match_regex: '^pr-(\d+)$|^(\d+)$'
        do_delete: "true"

  #----------------------------------------------------------------------------
  # Cleanup untagged images
  #----------------------------------------------------------------------------

  cleanup-untagged-images:

      name: Cleanup untagged images
      runs-on: ubuntu-latest
      needs: cleanup-ephemeral-images

      steps:

      - name: Log into registry ghcr.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_DELETE_TOKEN }}

      - name: Clean untagged images
        uses: stumpylog/image-cleaner-action/untagged@v0.10.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          owner: "h0tbird"
          is_org: "false"
          package_name: "k-swarm"
          do_delete: "true"
